//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class igroup193DBcontext : DbContext
    {
        public igroup193DBcontext()
            : base("name=igroup193DBcontext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
